services:
#  ms3:
#    build: "M:/40041165/SpringProjects/service-registry"
#    ports:
#      - "8761:8761"
#    networks:
#      - s-network
  ms1:
    build: .
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ms3:8761/eureka
    ports:
      - "8090:8090"
    networks:
      - s-network
  ms2:
    build: "M:/40041165/SpringProjects/question-service"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ms3:8761/eureka

    ports:
      - "8080:8080"
    networks:
      - s-network



  DB1:
    image: postgres:latest
    environment:
      POSTGRES_USER: nrupen
      POSTGRES_PASSWORD: nrupen123
      POSTGRES_DB: demo
    ports:
      - 5433:5432
    networks:
      - s-network
  DB2:
    image: postgres:latest
    environment:
      POSTGRES_USER: nrupen
      POSTGRES_PASSWORD: nrupen123
      POSTGRES_DB: quizDB
    ports:
      - 5434:5432
    networks:
      - s-network





networks:
  s-network:
    driver: bridge
    external: true